# Generated by Django 5.2.5 on 2026-02-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_underconstruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('home_para', 'Home Paragraph'), ('home_img', 'Home Image'), ('contact', 'Contact No'), ('email', 'Email'), ('address', 'Address')], max_length=255, unique=True)),
                ('home_imge', models.ImageField(blank=True, upload_to='home_image/')),
                ('text', models.TextField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
