# Generated by Django 5.2.5 on 2026-02-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_sitedatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedatamodel',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
